/****************************************************************/
/*               DO NOT MODIFY THIS HEADER                      */
/* MOOSE - Multiphysics Object Oriented Simulation Environment  */
/*                                                              */
/*           (c) 2010 Battelle Energy Alliance, LLC             */
/*                   ALL RIGHTS RESERVED                        */
/*                                                              */
/*          Prepared by Battelle Energy Alliance, LLC           */
/*            Under Contract No. DE-AC07-05ID14517              */
/*            With the U. S. Department of Energy               */
/*                                                              */
/*            See COPYRIGHT for full restrictions               */
/****************************************************************/

#ifndef CONVECTBC_H
#define CONVECTBC_H

#include "IntegratedBC.h"

//Forward Declarations
class ConvectBC;

template<>
InputParameters validParams<ConvectBC>();

/**
 * Implements a Robin condition where a heat loss is generated by conduction
 */
class ConvectBC: public IntegratedBC
{
public:

  /**
   * Factory constructor, takes parameters so that all derived classes can be built using the same
   * constructor.
   */
  ConvectBC(const InputParameters & parameters);

protected:
  virtual Real computeQpResidual();
  virtual Real Jacobian();

private:
  
  // Convection parameters
  const Real & _mu;
  Function & _u_e;

};

#endif //CONVECTBC_H
