#include "RavenApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<RavenApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

RavenApp::RavenApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  RavenApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  RavenApp::associateSyntax(_syntax, _action_factory);
}

RavenApp::~RavenApp()
{
}

void
RavenApp::registerApps()
{
  registerApp(RavenApp);
}

void
RavenApp::registerObjects(Factory & factory)
{
}

void
RavenApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
