#include "TurkeyApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<TurkeyApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

TurkeyApp::TurkeyApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  TurkeyApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  TurkeyApp::associateSyntax(_syntax, _action_factory);
}

TurkeyApp::~TurkeyApp()
{
}

// External entry point for dynamic application loading
extern "C" void TurkeyApp__registerApps() { TurkeyApp::registerApps(); }
void
TurkeyApp::registerApps()
{
  registerApp(TurkeyApp);
}

// External entry point for dynamic object registration
extern "C" void TurkeyApp__registerObjects(Factory & factory) { TurkeyApp::registerObjects(factory); }
void
TurkeyApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void TurkeyApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { TurkeyApp::associateSyntax(syntax, action_factory); }
void
TurkeyApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
